apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  containers:
  - image: cnetsdiegom.azurecr.io/webapp-backend:0.1
    name: backend
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
