version: "3"

volumes:
  mongo_data:
  mongo_dump:

networks:
  backend:

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
      - mongo_dump:/dump
    command: mongod --smallfiles --oplogSize 128
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend
  backend:
    image: diegom.azurecr.io/apidemo-backend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend
    ports:
      - "8082:8080"
  