version: "3"

volumes:
  mongo_data:
  mongo_dump:

networks:
  backend:
  frontend:

services:
  mongo:
    image:  cnetsdiegom.azurecr.io/webapp-mongo:0.1# mongo:latest
    volumes:
      - mongo_data:/data/db
      - mongo_dump:/dump
    command: mongod --smallfiles --oplogSize 128
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend
  backend:
    image: cnetsdiegom.azurecr.io/webapp-backend:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
  frontend:
    image: cnetsdiegom.azurecr.io/webapp-frontend:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    ports:
      - "80:80"
  