apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apidemo-backend
spec:
  template:
    metadata:
      labels:
        app: apidemo-backend
    spec:
      containers:
      - image: diegom.azurecr.io/apidemo-backend:latest
        name: apidemo-backend
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: MONGO_URL
          value: "${MONGO_URL}"
---
apiVersion: v1
kind: Service
metadata:
  name: apidemo-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apidemo-backend
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apidemo-backend
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: apidemo-backend.9c46259a61684ebcbee7.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: apidemo-backend
          servicePort: 80
        path: /*