apiVersion: v1
kind: Pod
metadata:
  labels:
    app: apidemo-frontend
  name: frontend
spec:
  containers:
  - image: diegom.azurecr.io/apidemo-frontend:latest
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
