apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
  - image: cnetsdiegom.azurecr.io/webapp-frontend:0.1
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
