apiVersion: v1
kind: Service
metadata:
  labels:
    app: apidemo-frontend
  name: frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: apidemo-frontend
status:
  loadBalancer: {}
