export const ActionTypes = {
  GET_STREAMS: 'GET_STREAMS',
  CREATE_STREAM: 'CREATE_STREAM',
  SELECT_STREAM: 'SELECT_STREAM',
  GET_MESSAGES: 'GET_MESSAGES',
  SET_REPLYMESSAGEID: 'SET_REPLYMESSAGEID',
};

export const KeyCode = {
  ENTER: 13,
};
